use crate::types::{ParameterSpec, Domain, ValueRange};
/// 领域H：身体-环境耦合 —— 身体与环境如何交互影响心理参数（全部0.95，人人都有）
pub fn domain_h_params() -> Vec<ParameterSpec> { vec![
ParameterSpec::atomic("H067","坐姿-思维关联强度",Domain::H,"身体坐姿(前倾/后仰/蜷缩/挺直)对思维模式(分析/发散/防御/自信)的影响强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["C025"],"H067↑ + C025b→-1","蜷缩坐姿强化社交回避").with_collapse("突然的环境变化(如被注视)可导致坐姿-思维关联暂时断裂").with_drift("随年龄上升——身体-心理耦合越来越紧密").with_drift("可通过身体觉察训练调节").with_age_drift(0.002),
ParameterSpec::atomic("H068","呼吸-情绪耦联强度",Domain::H,"呼吸模式(浅快/深慢/不规则)与情绪状态(焦虑/平静/愤怒)之间的双向耦合强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["A003"],"H068↑ + A003↑","高内感受+高呼吸耦联=通过呼吸精准调节情绪").with_coupling(vec!["B014"],"H068↑ + B014↑","呼吸作为情绪调节策略的有效性").with_collapse("惊恐发作时耦联可能断裂(呼吸失控但情绪冻结)").with_drift("可通过呼吸训练(如pranayama)增强").with_drift("慢性压力下耦联可能紊乱").with_age_drift(0.001),
ParameterSpec::atomic("H069","手势-语速锁定度",Domain::H,"手部动作节奏与语言输出速度之间的同步锁定程度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["F060"],"H069↑ + F060↑","手势-语速高度同步=表达更流畅更有说服力").with_coupling(vec!["C030c"],"H069↓ + C030c↓","手势与语速脱节=言语冲动控制差").with_collapse("高度紧张时锁定可能断裂(手势僵硬但语速加快)").with_drift("随社交经验积累通常上升").with_age_drift(0.001),
ParameterSpec::atomic("H070","温度-社交距离映射",Domain::H,"环境温度对社交距离偏好(物理距离/心理距离)的影响强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["C025b"],"H070↑ + C025b→+1","温暖环境强化社交趋近").with_coupling(vec!["F061"],"H070↑ + F061↑","温暖环境提升初始信任").with_collapse("极端温度(酷热/严寒)下社交距离偏好可能反转").with_drift("随年龄对温度-社交耦合的敏感度下降").with_age_drift(-0.001),
ParameterSpec::atomic("H071","饱腹-慷慨耦合",Domain::H,"血糖水平/饱腹感对资源共享/慷慨行为的影响强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["C035"],"H071↑ + C035↑","饱腹时利他惩罚倾向更强").with_coupling(vec!["C027"],"H071↑ + C027↓","饱腹时更愿意等待未来奖赏").with_collapse("极度饥饿时慷慨行为可能急剧下降(生存优先)").with_drift("随年龄对饥饿-慷慨耦合的敏感度上升").with_age_drift(0.001),
ParameterSpec::atomic("H072","昼夜节律-创造力相位",Domain::H,"创造力峰值在昼夜周期中的相位偏移（0=清晨峰值，0.5=正午，1=深夜峰值）",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["C038c"],"H072→深夜 + C038c↑","深夜认知刺激寻求更强").with_coupling(vec!["D042"],"H072→清晨 + D042↑","清晨行为灵活性更高").with_collapse("跨时区旅行/轮班工作可导致相位紊乱").with_drift("青春期向深夜偏移；中年后向清晨偏移").with_age_drift(-0.003),
ParameterSpec::atomic("H073","微表情抑制力",Domain::H,"抑制面部微表情(真实情绪的短暂泄露)的能力强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["F059"],"H073↑ + F059↑","高抑制+高欺骗舒适=完美的表情控制").with_coupling(vec!["F056"],"H073↑ + F056↑","高抑制+高镜像延迟=面部表情独立于社交环境").with_collapse("极度情绪冲击下微表情抑制可能崩溃").with_drift("随社交经验积累通常上升").with_drift("可通过表情管理训练提升").with_age_drift(0.002),
ParameterSpec::atomic("H074","疼痛-攻击链接强度",Domain::H,"身体疼痛体验触发/增强攻击行为的耦合强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["B019"],"H074↑ + B019↑","疼痛直接转化为攻击行为").with_coupling(vec!["C030a"],"H074↑ + C030a↓","疼痛→攻击几乎没有缓冲").with_collapse("慢性疼痛可能导致链接反转(疼痛→退缩而非攻击)").with_drift("随年龄疼痛-攻击链接通常减弱").with_age_drift(-0.002),
ParameterSpec::atomic("H075","光照-决策速度耦合",Domain::H,"环境光照强度对决策速度的影响强度（亮→快，暗→慢/谨慎）",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["C030"],"H075↑ + C030↓","强光下冲动控制进一步减弱").with_coupling(vec!["D042"],"H075↑ + D042↑","强光下行为灵活性更高").with_collapse("从暗到亮的突然切换可导致决策速度跳变").with_drift("随年龄对光照-决策耦合的敏感度下降").with_age_drift(-0.001),
ParameterSpec::atomic("H076","运动-情绪提升效率",Domain::H,"身体运动(有氧/力量/柔韧)对积极情绪的提升幅度和速度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["B018"],"H076↑ + B018↑","运动后积极情绪维持更久").with_coupling(vec!["B011_joy"],"H076↑ + 喜阈↓","运动降低喜悦唤醒阈值").with_collapse("过度运动(耗竭)后情绪提升可能反转为情绪低落").with_drift("随年龄运动-情绪提升效率通常下降").with_drift("规律运动可维持效率").with_age_drift(-0.001),
ParameterSpec::atomic("H077","睡眠债务-认知衰减率",Domain::H,"每单位睡眠债务(小时)导致的认知功能衰减速率",ValueRange::FloatPercent{min:1.0,max:30.0}).with_activation(0.95).with_coupling(vec!["A006"],"H077↑ + A006↓","睡眠不足时背景-前景分离效率急剧下降").with_coupling(vec!["C030"],"H077↑ + C030↓","睡眠不足时冲动控制崩溃").with_collapse("连续72小时不睡后认知功能可能断崖式下跌").with_drift("随年龄对睡眠债务的耐受度下降(衰减率上升)").with_age_drift(0.05),
ParameterSpec::atomic("H078","噪音-压力耦联强度",Domain::H,"环境噪音水平对压力激素/主观紧张感的触发强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["A005a"],"H078↑ + A005a↓","高噪音耦联+低听觉打断阈值=极易被噪音干扰").with_coupling(vec!["B011_fear"],"H078↑ + 惧阈↓","噪音触发恐惧反应").with_collapse("突然的巨响可导致耦联瞬间激活(惊吓反应)").with_drift("长期暴露于噪音环境中耦联可能下降(习惯化)或上升(敏化)").with_age_drift(0.0),
ParameterSpec::atomic("H079","气味-记忆唤起率",Domain::H,"嗅觉刺激触发自传体记忆(特别是情绪记忆)的概率和强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["E044a"],"H079↑ + E044a↑","气味触发过去事件反刍").with_coupling(vec!["B013a"],"H079↑ + B013a↑","气味触发的记忆携带强烈情绪附着力").with_collapse("创伤相关气味可触发闪回(唤起率跳变到极高)").with_drift("随年龄气味-记忆唤起率通常下降(嗅觉衰退)").with_age_drift(-0.002),
ParameterSpec::atomic("H080","触觉-信任关联强度",Domain::H,"身体接触(握手/拥抱/拍肩)对信任建立的促进强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["F061"],"H080↑ + F061↑","触觉促进初始信任建立").with_coupling(vec!["C033"],"H080↑ + C033↑","触觉强化亲和动机").with_collapse("被不信任者触碰时关联可能反转(触碰→警觉)").with_drift("随年龄触觉-信任关联通常减弱").with_drift("文化背景影响关联基线").with_age_drift(-0.001),
ParameterSpec::atomic("H081","饥饿-风险偏好偏移",Domain::H,"饥饿状态对风险决策的偏移方向和幅度（正=更冒险，负=更保守）",ValueRange::FloatNeg1Pos1).with_activation(0.95).with_coupling(vec!["C027"],"H081→+1 + C027→1","饥饿+高折扣=极度短视冒险").with_coupling(vec!["C038"],"H081→+1 + C038↑","饥饿+高刺激寻求=高风险行为").with_collapse("极度饥饿时风险偏好可能从冒险反转为保守(能量保存)").with_drift("随年龄饥饿-风险耦合通常减弱").with_age_drift(-0.001),
ParameterSpec::atomic("H082","姿势-权力感映射强度",Domain::H,"身体姿势(扩张/收缩)对主观权力感/自信的映射强度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["C031"],"H082↑ + C031↑","扩张姿势强化支配倾向").with_coupling(vec!["E046"],"H082↑ + E046↑","扩张姿势提升外显自尊").with_collapse("在权力不对等情境中映射可能被压制(低位者扩张姿势不产生权力感)").with_drift("随年龄姿势-权力映射通常减弱").with_age_drift(-0.001),
ParameterSpec::atomic("H083","温度-攻击性耦合",Domain::H,"环境温度(特别是高温)对攻击行为触发阈值的降低幅度",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["B019"],"H083↑ + B019↑","高温+高攻击转化=热浪暴力").with_coupling(vec!["C030a"],"H083↑ + C030a↓","高温+低攻击缓冲=冲动暴力").with_collapse("极端高温(>40°C)下攻击性可能跳变式上升").with_drift("随年龄温度-攻击耦合通常减弱").with_age_drift(-0.002),
ParameterSpec::atomic("H084","海拔-思维抽象度偏移",Domain::H,"物理高度/海拔对思维抽象程度的影响（高海拔→更抽象/大局观，低海拔→更具体/细节）",ValueRange::Float01).with_activation(0.95).with_coupling(vec!["C026c"],"H084↑ + C026c↑","高海拔强化对世界/宇宙的意义追问").with_coupling(vec!["E054"],"H084↑ + E054↑","高海拔提升框架重构力").with_collapse("极高海拔(缺氧)时思维抽象度可能崩溃(认知功能下降)").with_drift("随年龄海拔-抽象耦合通常减弱").with_age_drift(-0.001),
] }
